#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    url: jdbc:postgresql://localhost:5432/itemservice
#    username: sa
#    password:
#    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        transaction.interceptor: TRACE
        jdbc.datasource.DataSourceTransactionManager: DEBUG
        #JPA log
        orm.jpa.JpaTransactionManager: DEBUG
      #Sql log
      hibernate:
        resource.transaction: DEBUG
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE