#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    url: jdbc:postgresql://localhost:5432/itemservice
#    username: sa
#    password:
#    driver-class-name: org.postgresql.Driver
#Sql log
logging:
  level:
    org:
      springframework:
        transaction.interceptor: TRACE
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE